# Generated by Django 4.2.17 on 2024-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(max_length=4),
        ),
    ]
