# Generated by Django 4.2.17 on 2024-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_card_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
